### ISSUE TITLE
Error: Session store not set on request

### ISSUE THREAD

**Issue by AlexKazm** [xterm-inator/MikroGuard#39]
Still struggling with the problem, according to your notes, I checked APP_URL, without success. I also played around with ports and also without success. There are thoughts in what can be.

**Comment by AlexKazm** [comment]
By the way, the web panel should start even if you did not correctly specify the data for Mikrotik?

**Comment by xterm-inator** [comment]
hey,

> By the way, the web panel should start even if you did not correctly specify the data for Mikrotik?

Yes and you will be able to login but after that the pages will not work correctly.


> Still struggling with the problem, according to your notes, I checked APP_URL, without success. I also played around with ports and also without success. There are thoughts in what can be.

The main thing for this error is if you can see the login page in your browser, then copy that url and past it into the APP_URL env (including the http\s://) then restart the container and it should work.
