### ISSUE TITLE
PersistentKeepalive option

### ISSUE THREAD

**Issue by alexanderek** [xterm-inator/MikroGuard#55]
Hello!

Is it possible to add PersistentKeepalive to the config ?

**Comment by xterm-inator** [comment]
Hey,

I have made an update to add this to the peer config.

If this is what you were after could you give ghcr.io/xterm-inator/mikroguard:pr-56 a try and see if that works for you. You will need to add ROUTEROS_WIREGUARD_PERSISTENT_KEEPALIVE=25 to your env and recreate your peer config in mikroguard for it the be added to both the server and client peers

**Comment by alexanderek** [comment]
I tested it, and it works perfectly! Thank you for the update and the help.

**Comment by xterm-inator** [comment]
Hey, Thanks for testing. 
I have now released this update. 
you can update your docker image path to latest or 1.3.2. No other changes are required.

Thanks
